root: true
env:
  commonjs: true
  browser: true
  es2021: true
  mocha: true
  node: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
extends:
  - airbnb-base
  - prettier
plugins:
  - import
globals:
  expect: readonly
  supertest: readonly
  NODE_ENV: readonly
  TEST_DB_URL: readonly
ignorePatterns:
  - '/*'
  - '!db/'
  - '!src/'
  - '!tests/'
  - 'db/**.csv'
rules:
  camelcase: 0
  comma-dangle: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  linebreak-style:
    - error
    - unix
  no-plusplus: 0
  no-return-assign: 0
  no-param-reassign: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
  import/no-useless-path-segments: 0
